// Generated by Supabase CLI (manually adapted)
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      workspaces: {
        Row: {
          id: string
          user_id: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
      }
      drafts: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          name: string
          versions: Json[]
          current_version: number
          status: string
          platforms: Json[]
          content_type: string | null
          scheduled_at: string | null
          published_at: string | null
          publish_results: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          name: string
          versions?: Json[]
          current_version?: number
          status?: string
          platforms?: Json[]
          content_type?: string | null
          scheduled_at?: string | null
          published_at?: string | null
          publish_results?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          name?: string
          versions?: Json[]
          current_version?: number
          status?: string
          platforms?: Json[]
          content_type?: string | null
          scheduled_at?: string | null
          published_at?: string | null
          publish_results?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      brand_kits: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          name: string
          data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          name: string
          data?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          name?: string
          data?: Json
          created_at?: string
          updated_at?: string
        }
      }
      chat_threads: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          data: Json[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          data?: Json[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          data?: Json[]
          created_at?: string
          updated_at?: string
        }
      }
      system_configs: {
        Row: {
          key: string
          value: Json
          updated_at: string
        }
        Insert: {
          key: string
          value?: Json
          updated_at?: string
        }
        Update: {
          key?: string
          value?: Json
          updated_at?: string
        }
      }
      evolution_logs: {
        Row: {
          id: string
          version: string
          change_type: string
          description: string
          diff: Json | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          version: string
          change_type: string
          description: string
          diff?: Json | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          version?: string
          change_type?: string
          description?: string
          diff?: Json | null
          status?: string
          created_at?: string
        }
      }
      approval_queue: {
        Row: {
          id: string
          content: string
          metadata: Json
          status: string
          decision_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          content: string
          metadata?: Json
          status?: string
          decision_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          content?: string
          metadata?: Json
          status?: string
          decision_reason?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      orchestration_plans: {
        Row: {
          id: string
          user_request: string
          plan_data: Json
          status: string
          final_output: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_request: string
          plan_data?: Json
          status?: string
          final_output?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_request?: string
          plan_data?: Json
          status?: string
          final_output?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}