import type { PlatformConfig, Platform } from '@/lib/types';

export const PLATFORMS: Record<Platform, PlatformConfig> = {
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    icon: 'twitter',
    maxLength: 280,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    maxLength: 2200,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['1:1', '4:5', '9:16'],
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: 'tiktok',
    maxLength: 2200,
    supportsImages: false,
    supportsVideo: true,
    aspectRatios: ['9:16'],
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    maxLength: 3000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['1:1', '16:9', '1.91:1'],
  },
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    icon: 'facebook',
    maxLength: 63206,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1', '4:5'],
  },
  threads: {
    id: 'threads',
    name: 'Threads',
    icon: 'threads',
    maxLength: 500,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['1:1', '4:5'],
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    icon: 'youtube',
    maxLength: 5000,
    supportsImages: false,
    supportsVideo: true,
    aspectRatios: ['16:9', '9:16'],
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    icon: 'pinterest',
    maxLength: 500,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['2:3', '1:1'],
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    icon: 'discord',
    maxLength: 2000,
    supportsImages: true,
    supportsVideo: false,
    aspectRatios: ['1:1'],
  },
  reddit: {
    id: 'reddit',
    name: 'Reddit',
    icon: 'reddit',
    maxLength: 40000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: 'whatsapp',
    maxLength: 65536,
    supportsImages: true,
    supportsVideo: false,
    aspectRatios: ['1:1'],
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    icon: 'telegram',
    maxLength: 4096,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    icon: 'snapchat',
    maxLength: 1000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['9:16', '1:1'],
  },
  wordpress: {
    id: 'wordpress',
    name: 'WordPress',
    icon: 'wordpress',
    maxLength: 50000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  medium: {
    id: 'medium',
    name: 'Medium',
    icon: 'medium',
    maxLength: 100000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  ghost: {
    id: 'ghost',
    name: 'Ghost',
    icon: 'ghost',
    maxLength: 50000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  substack: {
    id: 'substack',
    name: 'Substack',
    icon: 'substack',
    maxLength: 100000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1'],
  },
  mailchimp: {
    id: 'mailchimp',
    name: 'Mailchimp',
    icon: 'mailchimp',
    maxLength: 10000,
    supportsImages: true,
    supportsVideo: false,
    aspectRatios: ['1:1'],
  },
  klaviyo: {
    id: 'klaviyo',
    name: 'Klaviyo',
    icon: 'klaviyo',
    maxLength: 10000,
    supportsImages: true,
    supportsVideo: false,
    aspectRatios: ['1:1'],
  },
  convertkit: {
    id: 'convertkit',
    name: 'ConvertKit',
    icon: 'convertkit',
    maxLength: 10000,
    supportsImages: true,
    supportsVideo: false,
    aspectRatios: ['1:1'],
  },
  general: {
    id: 'general',
    name: 'General',
    icon: 'globe',
    maxLength: 10000,
    supportsImages: true,
    supportsVideo: true,
    aspectRatios: ['16:9', '1:1', '4:5'],
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export const DEFAULT_POSTING_TIMES: Record<Platform, string[]> = {
  twitter: ['09:00', '13:00', '18:00'],
  instagram: ['11:00', '14:00', '19:00'],
  tiktok: ['07:00', '15:00', '21:00'],
  linkedin: ['08:00', '12:00', '17:00'],
  facebook: ['09:00', '13:00', '16:00'],
  threads: ['10:00', '14:00', '20:00'],
  youtube: ['14:00', '17:00'],
  pinterest: ['20:00', '21:00'],
  discord: ['10:00', '15:00', '19:00'],
  reddit: ['08:00', '12:00', '18:00'],
  whatsapp: ['09:00', '13:00', '18:00'],
  telegram: ['10:00', '14:00', '19:00'],
  snapchat: ['12:00', '16:00', '20:00'],
  wordpress: ['08:00', '12:00'],
  medium: ['09:00', '15:00'],
  ghost: ['08:00', '12:00'],
  substack: ['07:00', '18:00'],
  mailchimp: ['10:00'],
  klaviyo: ['10:00'],
  convertkit: ['10:00'],
  general: ['09:00', '14:00', '18:00'],
};
