'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { CheckCircle2, XCircle, Clock, MessageSquare } from 'lucide-react';
import { toast } from 'sonner';

interface ApprovalItem {
  id: string;
  content: string;
  metadata: {
    platform: string;
    agentRole: string;
    modelUsed: string;
    score: number;
    createdAt: string;
  };
  status: 'pending' | 'approved' | 'rejected';
}

export default function ApprovalQueuePage() {
  const [items, setItems] = useState<ApprovalItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [feedback, setFeedback] = useState<Record<string, string>>({});

  useEffect(() => {
    fetchQueue();
  }, []);

  async function fetchQueue() {
    setLoading(true);
    try {
      const res = await fetch('/api/approval');
      const data = await res.json();
      setItems(data);
    } catch (err) {
      toast.error('Failed to load approval queue');
    } finally {
      setLoading(false);
    }
  }

  async function handleDecision(id: string, status: 'approved' | 'rejected') {
    try {
      const res = await fetch('/api/approval', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          id, 
          status, 
          feedback: feedback[id] 
        }),
      });

      if (res.ok) {
        toast.success(`Item ${status === 'approved' ? 'approved' : 'rejected'}`);
        await fetchQueue();
      } else {
        toast.error('Decision failed to save');
      }
    } catch (err) {
      toast.error('Network error occurred');
    }
  }

  if (loading) return <div className="p-8 text-center">Loading Approval Queue...</div>;

  return (
    <div className="p-8 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Approval Queue</h1>
          <p className="text-muted-foreground">Review and authorize content generated by the Manager.</p>
        </div>
        <Button variant="outline" onClick={fetchQueue}>Refresh</Button>
      </div>

      {items.length === 0 ? (
        <Card className="text-center p-12">
          <CardContent>
            <Clock className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
            <p className="text-xl font-medium">No pending approvals</p>
            <p className="text-muted-foreground">Everything is currently up to date.</p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-6">
          {items.map((item) => (
            <Card key={item.id} className="overflow-hidden border-l-4 border-l-primary">
              <CardHeader className="bg-muted/30">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="text-lg">Generated Content</CardTitle>
                    <CardDescription className="flex gap-2 mt-1">
                      <Badge variant="outline">{item.metadata.platform}</Badge>
                      <Badge variant="secondary">{item.metadata.agentRole}</Badge>
                      <span className="text-xs text-muted-foreground">
                        Model: {item.metadata.modelUsed} | Score: {item.metadata.score}
                      </span>
                    </CardDescription>
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {new Date(item.metadata.createdAt).toLocaleString()}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-6 space-y-4">
                <div className="p-4 bg-background rounded-lg border whitespace-pre-wrap font-serif text-lg">
                  {item.content}
                </div>
                
                <div className="flex gap-4 items-start">
                  <div className="flex-1 relative">
                    <MessageSquare className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                    <Textarea 
                      placeholder="Add feedback for the Manager..." 
                      className="pl-9"
                      value={feedback[item.id] || ''}
                      onChange={(e) => setFeedback(prev => ({ ...prev, [item.id]: e.target.value }))}
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      variant="destructive" 
                      className="gap-2"
                      onClick={() => handleDecision(item.id, 'rejected')}
                    >
                      <XCircle className="h-4 w-4" /> Reject
                    </Button>
                    <Button 
                      className="gap-2" 
                      onClick={() => handleDecision(item.id, 'approved')}
                    >
                      <CheckCircle2 className="h-4 w-4" /> Approve
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
